CRITICAL - 2022-05-18 12:24:38 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->LoginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:27:51 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:28:48 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:28:55 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:29:36 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:32:39 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:33:51 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:38:57 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:39:22 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:39:48 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:45:56 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:46:08 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:47:14 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:50:57 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:50:59 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:51:02 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:51:21 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:51:26 --> Call to a member function query() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:53:05 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:53:15 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:53:38 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:53:44 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:53:49 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:54:51 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:55:00 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:55:03 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:55:19 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 12:55:47 --> Call to a member function model() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->loginUser()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 13:03:42 --> Undefined property: App\Controllers\Auth::$load
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 21, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:10:12 --> Undefined property: App\Controllers\Auth::$load
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(15): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(889): App\Controllers\Auth->__construct()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:10:45 --> Undefined property: App\Controllers\Auth::$load
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(15): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(889): App\Controllers\Auth->__construct()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:11:02 --> Undefined property: App\Controllers\Auth::$Login_model
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:11:27 --> Undefined property: App\Controllers\Auth::$UserModel
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:19:20 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:20:07 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:20:58 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:21:05 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:21:36 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:21:43 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:25:24 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:25:49 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:27:49 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:49:25 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 13:50:29 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:12:30 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:13:31 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:15:21 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:16:29 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:16:31 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:19:21 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:19:31 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:24:58 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:25:22 --> Call to undefined method App\Models\UserModel::wrhere
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('wrhere', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:27:13 --> Call to undefined method App\Models\UserModel::whereHas
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(27): CodeIgniter\Model->__call('whereHas', Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:30:19 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:30:56 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:31:20 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:32:01 --> Undefined property: App\Controllers\Auth::$load
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(15): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(889): App\Controllers\Auth->__construct()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:33:39 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 14:33:58 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 14:34:12 --> Call to a member function where() on null
#0 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-18 14:36:15 --> Undefined property: App\Controllers\Auth::$load
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(14): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(889): App\Controllers\Auth->__construct()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 14:38:20 --> Undefined property: App\Controllers\Auth::$load
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(14): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(889): App\Controllers\Auth->__construct()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:06:53 --> Undefined property: App\Controllers\Auth::$load
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(14): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(889): App\Controllers\Auth->__construct()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:07:51 --> Undefined property: App\Controllers\Auth::$UserModel
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(29): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 29, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:34:58 --> Trying to get property 'email' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 22, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:35:06 --> Trying to get property 'email' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 22, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:37:34 --> Trying to get property 'email' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 22, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:41:30 --> Trying to get property 'email' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:42:29 --> Trying to get property 'emails' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:42:40 --> Trying to get property 'emails' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:44:07 --> Trying to get property 'emails' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:44:14 --> Trying to get property 'emails' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:44:41 --> Trying to get property 'username' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:46:40 --> Trying to get property 'username' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:47:00 --> Trying to get property 'username' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:47:04 --> Trying to get property 'username' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:47:20 --> Trying to get property 'password' of non-object
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:51:06 --> Argument 3 passed to CodeIgniter\RESTful\ResourceController::respond() must be of the type string, array given, called in C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php on line 49
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(49): CodeIgniter\RESTful\ResourceController->respond(Array, 200, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:53:42 --> Array to string conversion
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 48, Array)
#1 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(48): implode('\\', Array)
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-05-18 15:55:03 --> Array to string conversion
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 48, Array)
#1 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(48): implode('\\', Array)
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-05-18 15:55:43 --> Array to string conversion
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 48, Array)
#1 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(48): implode('\\', Array)
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-05-18 15:55:53 --> Array to string conversion
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 48, Array)
#1 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(48): implode('\\', Array)
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-05-18 15:57:31 --> Array to string conversion
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 48, Array)
#1 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(48): implode('\\', Array)
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-05-18 15:58:16 --> syntax error, unexpected ';', expecting ')'
#0 C:\xampp\htdocs\loginshwt\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('Auth/create')
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(792): CodeIgniter\Router\Router->handle('Auth/create')
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(363): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-18 15:58:43 --> Array to string conversion
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 48, Array)
#1 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(48): implode('\\', Array)
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-05-18 15:59:11 --> Array to string conversion
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 48, Array)
#1 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(48): implode('\\', Array)
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-05-18 16:00:03 --> Argument 3 passed to CodeIgniter\RESTful\ResourceController::respond() must be of the type string, array given, called in C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php on line 50
#0 C:\xampp\htdocs\loginshwt\app\Controllers\Auth.php(50): CodeIgniter\RESTful\ResourceController->respond(Array, 200, Array)
#1 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(917): App\Controllers\Auth->create()
#2 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\loginshwt\system\CodeIgniter.php(311): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loginshwt\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\loginshwt\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
